# Experiment settings
experiment:
  name: resnet20_cifar10_paper_config_no_smooth
  recononly: 0
  num_epochs: 200
  log_interval: 100
  eval_interval: 1
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet20
  pretrained_path: resnet20-12fca82f.th  # Path to pre-trained model
  smooth: False

# Training configurations
training:
  optimizer: 'adam'
  learning_rate: 1e-3
  batch_size: 128
  coordinate_noise: 0.001
  scheduler: cosine # Change scheduler into cosine 
  T_max: 200
  # lr_steps: [100, 150]
  weight_decay: 1e-3
  # strong_aug: v1 # Adding more augmentation to test the result
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet20_cifar10_paper_config_no_smooth # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp # resmlp in paper
  input_dim: 6  # Input tensors (the coordinate)
  hidden_dim: 256
  num_layers: 5  # change to 5 from 4
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

  loss_weight:
    ce_weight: 1.0
    reg_weight: 0.0001
    recon_weight: 1.0
    kd_weight: 0.1

# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension